# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='replay_text',
            field=models.TextField(default='null', max_length=250),
        ),
    ]
