# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170209_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='replay_text',
            field=models.TextField(max_length=250, null=True),
        ),
    ]
