# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170209_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
