# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170209_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForbiddenWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forbiddenWord', models.CharField(max_length=180)),
            ],
        ),
        migrations.AlterField(
            model_name='reply',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
